// Code generated by "stringer -type=TokenKind -trimprefix Token ./lexer"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenErr-0]
	_ = x[TokenBraceOpen-1]
	_ = x[TokenBraceClose-2]
	_ = x[TokenNewLine-3]
	_ = x[TokenHorizontalLine-4]
	_ = x[TokenPreformattedFence-5]
	_ = x[TokenPreformattedAltText-6]
	_ = x[TokenHeadingOpen-7]
	_ = x[TokenHeadingClose-8]
	_ = x[TokenSpanNewLine-9]
	_ = x[TokenSpanText-10]
	_ = x[TokenSpanItalic-11]
	_ = x[TokenSpanBold-12]
	_ = x[TokenSpanMonospace-13]
	_ = x[TokenSpanMarker-14]
	_ = x[TokenSpanSuper-15]
	_ = x[TokenSpanSub-16]
	_ = x[TokenSpanStrike-17]
	_ = x[TokenSpanUnderline-18]
	_ = x[TokenSpanLinkOpen-19]
	_ = x[TokenSpanLinkClose-20]
	_ = x[TokenLinkAddress-21]
	_ = x[TokenLinkDisplayOpen-22]
	_ = x[TokenLinkDisplayClose-23]
	_ = x[TokenAutoLink-24]
	_ = x[TokenRocketLinkOpen-25]
	_ = x[TokenRocketLinkClose-26]
	_ = x[TokenBlockQuoteOpen-27]
	_ = x[TokenBlockQuoteClose-28]
	_ = x[TokenBulletUnnumbered-29]
	_ = x[TokenBulletIndent-30]
	_ = x[TokenBulletNumberedImplicit-31]
	_ = x[TokenBulletNumberedExplicit-32]
	_ = x[TokenTagImg-33]
	_ = x[TokenTagTable-34]
	_ = x[TokenParagraphOpen-35]
	_ = x[TokenParagraphClose-36]
}

const _TokenKind_name = "ErrBraceOpenBraceCloseNewLineHorizontalLinePreformattedFencePreformattedAltTextHeadingOpenHeadingCloseSpanNewLineSpanTextSpanItalicSpanBoldSpanMonospaceSpanMarkerSpanSuperSpanSubSpanStrikeSpanUnderlineSpanLinkOpenSpanLinkCloseLinkAddressLinkDisplayOpenLinkDisplayCloseAutoLinkRocketLinkOpenRocketLinkCloseBlockQuoteOpenBlockQuoteCloseBulletUnnumberedBulletIndentBulletNumberedImplicitBulletNumberedExplicitTagImgTagTableParagraphOpenParagraphClose"

var _TokenKind_index = [...]uint16{0, 3, 12, 22, 29, 43, 60, 79, 90, 102, 113, 121, 131, 139, 152, 162, 171, 178, 188, 201, 213, 226, 237, 252, 268, 276, 290, 305, 319, 334, 350, 362, 384, 406, 412, 420, 433, 447}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
